/*
 * Copyright (c) 2026, WSO2 LLC. (http://www.wso2.org) All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package llmcost

import (
	"encoding/json"
	"strings"
)

// GeminiCalculator handles models with provider "gemini", "vertex_ai", and
// related subfamilies. Uses the "usageMetadata" response namespace.
// Grounding cost is applied in Adjust() as a fixed per-query fee.
type GeminiCalculator struct{}

// modalityTokenDetail is a single entry in Gemini's per-modality token arrays.
type modalityTokenDetail struct {
	Modality   string `json:"modality"`
	TokenCount int64  `json:"tokenCount"`
}

func (c *GeminiCalculator) Normalize(responseBody []byte, _ []byte) (Usage, error) {
	var resp struct {
		// candidates array: used for groundingMetadata (web search queries)
		Candidates []struct {
			GroundingMetadata struct {
				// WebSearchQueries is a list of search queries issued for grounding.
				// Google AI Studio bills $0.035 per query; Vertex AI bills $0.035 flat.
				WebSearchQueries []string `json:"webSearchQueries"`
			} `json:"groundingMetadata"`
		} `json:"candidates"`
		UsageMetadata struct {
			PromptTokenCount        int64 `json:"promptTokenCount"`
			CandidatesTokenCount    int64 `json:"candidatesTokenCount"`
			TotalTokenCount         int64 `json:"totalTokenCount"`
			ThoughtsTokenCount      int64 `json:"thoughtsTokenCount"`      // Gemini thinking models
			CachedContentTokenCount int64 `json:"cachedContentTokenCount"` // Gemini context caching

			// Prompt token breakdown by modality (TEXT / AUDIO / IMAGE / VIDEO).
			// Total counts (cached + non-cached); we subtract cacheTokensDetails below.
			PromptTokensDetails []modalityTokenDetail `json:"promptTokensDetails"`

			// Cached token breakdown by modality (explicit context caching only).
			CacheTokensDetails []modalityTokenDetail `json:"cacheTokensDetails"`

			// Candidate (output) token breakdown by modality.
			// Used by image-generation and native-audio output models.
			CandidatesTokensDetails []modalityTokenDetail `json:"candidatesTokensDetails"`

			// Gemini Live API only — output tokens with per-modality breakdown.
			ResponseTokenCount    int64                 `json:"responseTokenCount"`
			ResponseTokensDetails []modalityTokenDetail `json:"responseTokensDetails"`

			// Gemini Live API only — tokens generated by grounding / web search tools.
			// These are SEPARATE from promptTokenCount (not a subset) and represent
			// search result context injected back into the model.
			ToolUsePromptTokenCount int64 `json:"toolUsePromptTokenCount"`

			// Per-modality breakdown of toolUsePromptTokenCount (AUDIO, TEXT, etc.).
			// Parsed for completeness; all tool-use tokens are currently billed as a
			// unit via a flat fee or the standard input rate.
			ToolUsePromptTokensDetails []modalityTokenDetail `json:"toolUsePromptTokensDetails"`

			// trafficType indicates the Gemini service tier for this request.
			// Values: "ON_DEMAND" (default), "ON_DEMAND_PRIORITY", "FLEX", "BATCH".
			// Mapped to ServiceTier: "priority" or "flex" (ON_DEMAND → "").
			TrafficType string `json:"trafficType"`
		} `json:"usageMetadata"`
	}
	if err := json.Unmarshal(responseBody, &resp); err != nil {
		return Usage{}, err
	}
	m := resp.UsageMetadata

	// Prompt modality tokens: promptTokensDetails gives totals (including cached);
	// subtract cacheTokensDetails to get the non-cached portion billed at input rate.
	var rawAudioIn, rawImageIn int64
	for _, d := range m.PromptTokensDetails {
		switch d.Modality {
		case "AUDIO":
			rawAudioIn = d.TokenCount
		case "IMAGE":
			rawImageIn = d.TokenCount
		}
	}
	// Subtract cached tokens per modality (explicit context caching).
	var cachedAudioIn, cachedImageIn int64
	for _, d := range m.CacheTokensDetails {
		switch d.Modality {
		case "AUDIO":
			cachedAudioIn = d.TokenCount
		case "IMAGE":
			cachedImageIn = d.TokenCount
		}
	}
	audioIn := rawAudioIn - cachedAudioIn
	if audioIn < 0 {
		audioIn = 0
	}
	imageIn := rawImageIn - cachedImageIn
	if imageIn < 0 {
		imageIn = 0
	}

	// --- Output modality tokens ---
	// candidatesTokensDetails is used for image-generation and non-streaming audio models.
	// responseTokensDetails is used for Gemini Live (streaming audio).
	// We read both and take whichever is non-zero.
	var audioOut, imageOut int64
	for _, d := range m.CandidatesTokensDetails {
		switch d.Modality {
		case "AUDIO":
			audioOut = d.TokenCount
		case "IMAGE":
			imageOut = d.TokenCount
		}
	}
	// Gemini Live: responseTokensDetails overrides candidatesTokensDetails for audio
	for _, d := range m.ResponseTokensDetails {
		if d.Modality == "AUDIO" {
			audioOut = d.TokenCount
		}
	}

	// Use responseTokenCount (Gemini Live) when available.
	completionTokens := m.CandidatesTokenCount
	if m.ResponseTokenCount > 0 {
		completionTokens = m.ResponseTokenCount
	}

	// Gemini thinking models: thoughtsTokenCount may or may not be included in
	// candidatesTokenCount. When prompt + candidates == total it is inclusive;
	// otherwise it is a separate bucket and must be added to CompletionTokens.
	reasoningTokens := m.ThoughtsTokenCount
	if reasoningTokens > 0 {
		isInclusive := (m.PromptTokenCount + m.CandidatesTokenCount) == m.TotalTokenCount
		if !isInclusive {
			completionTokens += reasoningTokens
		}
	}

	// Map trafficType → ServiceTier string.
	var serviceTier string
	switch m.TrafficType {
	case "ON_DEMAND_PRIORITY":
		serviceTier = "priority"
	case "FLEX", "BATCH":
		serviceTier = "flex"
	}

	// Count grounding web search queries across all candidates.
	// Used in Adjust() to add the $0.035/query (Google AI Studio) or $0.035 flat (Vertex AI) fee.
	var webSearchRequests int64
	for _, cand := range resp.Candidates {
		webSearchRequests += int64(len(cand.GroundingMetadata.WebSearchQueries))
	}

	return Usage{
		PromptTokens:            m.PromptTokenCount,
		CompletionTokens:        completionTokens,
		TotalTokens:             m.TotalTokenCount,
		ReasoningTokens:         reasoningTokens,
		CachedReadTokens:        m.CachedContentTokenCount,
		CachedAudioInputTokens:  cachedAudioIn,
		AudioInputTokens:        audioIn,
		AudioOutputTokens:       audioOut,
		ImageOutputTokens:       imageOut,
		ToolUsePromptTokens:     m.ToolUsePromptTokenCount,
		ServiceTier:             serviceTier,
		GeminiWebSearchRequests: webSearchRequests,
	}, nil
}

func (c *GeminiCalculator) Adjust(baseCost float64, usage Usage, pricing ModelPricing) float64 {
	total := baseCost

	// Grounding / web search cost: $0.035 per query (Google AI Studio) or $0.035
	// flat per call (Vertex AI), charged on top of token costs.
	const groundingCostPerQuery = 35e-3 // $0.035
	if usage.GeminiWebSearchRequests > 0 {
		if strings.HasPrefix(pricing.Provider, "vertex_ai") {
			// Vertex AI: flat fee regardless of how many search queries were issued
			total += groundingCostPerQuery
		} else {
			// Google AI Studio: per-query fee
			total += float64(usage.GeminiWebSearchRequests) * groundingCostPerQuery
		}
	}

	return total
}
